
@host = http://localhost:3000
@urlMovies = /api/movies
@urlCharacters = /api/characters
@urlUsers = /api/users


#####################################################################  MOVIES  ####################

### GET ALL
GET {{host}}{{urlMovies}}
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNywiZXhwIjoxNjgxNjY4NzE3LCJpYXQiOjE2ODEyMzY3MTd9.7gJIMT2Jr4JuJiThXhMtBUu5QT14yTV8JJpRZsw7f6Y

### POST 
POST {{host}}{{urlMovies}}/new
Content-Type: application/json

{
"title": "Harry Potter and the Deathly Hallows 2",
"year": 2011,
"image": "https://m.media-amazon.com/images/M/MV5BMGVmMWNiMDktYjQ0Mi00MWIxLTk0N2UtN2ZlYTdkN2IzNDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg"

}



###GET BY ID
GET {{host}}{{urlMovies}}/1



###
PUT {{host}}{{urlMovies}}/11
Content-Type: application/json

{
"title": "Esto es una prueba jeje",
"year": 2011,
"image": "https://m.media-amazon.com/images/M/MV5BMGVmMWNiMDktYjQ0Mi00MWIxLTk0N2UtN2ZlYTdkN2IzNDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg"

}



###
DELETE {{host}}{{urlMovies}}/10




###################################################################   CHARACTERS   #################


###
GET {{host}}{{urlCharacters}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNywiZXhwIjoxNjgxNjY4NzE3LCJpYXQiOjE2ODEyMzY3MTd9.7gJIMT2Jr4JuJiThXhMtBUu5QT14yTV8JJpRZsw7f6Y


### GET BY ID
GET {{host}}{{urlCharacters}}/25



###
PUT {{host}}{{urlCharacters}}/35
Content-Type: application/json

{
"name": "Draco Malfoy",
"type": "villain",
"image": "https://noelialopezcheda.files.wordpress.com/2015/12/una-foto-promo-di-draco-malfoy-tom-felton-per-il-film-harry-potter-e-la-pietra-filosofale-129105.jpg?w=640",
"status": "alive"
}



###
POST {{host}}{{urlCharacters}}/new
Content-Type: application/json

{
"name": "Draco Maldfoy",
"type": "villain",
"image": "https://noelialopezcheda.files.wordpress.com/2015/12/una-foto-promo-di-draco-malfoy-tom-felton-per-il-film-harry-potter-e-la-pietra-filosofale-129105.jpg?w=640",
"status": "alive"
}


###
DELETE {{host}}{{urlCharacters}}/34


##################################################   USERS   ##################################################

### NEW USER
POST {{host}}{{urlUsers}}/register
Content-Type: application/json

{
"username": "sara",
"email": "sara",
"password": "12345",
"role": "admin"

}


### LOGIN
POST {{host}}{{urlUsers}}/login
Content-Type: application/json

{
    "email": "marta@gmail.com",
    "password": "12345"
}
